/**
 * FILE: src/slices/usersSlice.ts
 * DESCRIPTION: Manages user data. Action creators are auto-generated by createSlice.
 * You can now safely delete src/actions/users.ts.
 */

import { createSlice, PayloadAction } from '@reduxjs/toolkit';

/**
 * Interface for an individual User object
 */
export interface User {
  id: string;
  name: string;
  avatarURL: string;
  answers: {
    [qid: string]: 'optionOne' | 'optionTwo';
  };
  questions: string[];
}

/**
 * Interface for the Users state object
 */
export interface UsersState {
  [key: string]: User;
}

/**
 * Interface for the payload when a user answers a question
 */
interface UserAnswerPayload {
  authedUser: string;
  qid: string;
  answer: 'optionOne' | 'optionTwo';
}

/**
 * Interface for the payload when a user creates a question
 */
interface UserQuestionPayload {
  authedUser: string;
  qid: string;
}

const initialState: UsersState = {};

const usersSlice = createSlice({
  name: 'users',
  initialState,
  reducers: {
    /**
     * Initial data load from _DATA.ts
     */
    receiveUsers(_state, action: PayloadAction<UsersState>) {
      return action.payload;
    },
    /**
     * Updates the user's answers mapping.
     * Called by handleAddAnswer thunk in questionsSlice.
     */
    addAnswerToUser(state, action: PayloadAction<UserAnswerPayload>) {
      const { authedUser, qid, answer } = action.payload;
      if (state[authedUser]) {
        state[authedUser].answers[qid] = answer;
      }
    },
    /**
     * Adds a question ID to the user's created questions array.
     * Called by handleAddQuestion thunk in questionsSlice.
     */
    addQuestionToUser(state, action: PayloadAction<UserQuestionPayload>) {
      const { authedUser, qid } = action.payload;
      if (state[authedUser]) {
        // Ensure we don't add duplicates if the thunk retries
        if (!state[authedUser].questions.includes(qid)) {
          state[authedUser].questions.push(qid);
        }
      }
    },
  },
});

export const { receiveUsers, addAnswerToUser, addQuestionToUser } = usersSlice.actions;
export default usersSlice.reducer;